### ISSUE TITLE
Cep não aceita números iniciados com "0" (zero)

### ISSUE THREAD

**Issue by felicioandre** [ricardorinco/viacep#1]
Pela demo, tentei adicionar um cep iniciado em 0, porém o input não entra o valor. Coloquei o meu CEP 06539-105. Daí com isso, o cep fica assim: "65391-05", e não acha nada.

**Comment by ricardorinco** [comment]
Obrigado pela observação @felicioandre, a correção foi realizada no commit 3c6bb35.
